#!/usr/bin/python2

"""
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
"""

from unittest import TestCase, main


class Problem2(object):
    def __init__(self, bound):
        self._bound = bound
        self._prev = 0
        self._current = 2

    def fn(self):
        total = 0
        while self._current < self._bound:
            total += self._current
            tmp = self._current
            self._current = 4 * self._current + self._prev
            self._prev = tmp
        return total


class TestProblem2(TestCase):
    def setUp(self):
        self.bound = 4000000
        self.answer = 4613732

    def test_fn(self):
        self.assertEqual(Problem2(self.bound).fn(), self.answer)


if __name__ == '__main__':
    main()
